sudo: false

language: java

env:
  global:
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE=""
    - ECLIPSE_RELEASE="-Declipse-release=juno"
    - ECLIPSE_RELEASE="-Declipse-release=kepler"
    - ECLIPSE_RELEASE="-Declipse-release=luna"
    - ECLIPSE_RELEASE="-Declipse-release=mars"
    - ECLIPSE_RELEASE="-Declipse-release=neon"

jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

script: mvn clean verify -f ch.acanda.eclipse.pmd/pom.xml -B -PskipSWTBot $ECLIPSE_RELEASE
