sudo: false

language: java

env:
  global:
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE=mars
    - ECLIPSE_RELEASE=neon

cache:
  directories:
    - $HOME/.m2

jdk: oraclejdk8

install: true

script: mvn clean install -B -Declipse-release=$ECLIPSE_RELEASE
