sudo: false

language: java

env:
  global:
    - DISPLAY=:99
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE=""
    - ECLIPSE_RELEASE="-Declipse-release=juno"
    - ECLIPSE_RELEASE="-Declipse-release=kepler"
    - ECLIPSE_RELEASE="-Declipse-release=luna"
    - ECLIPSE_RELEASE="-Declipse-release=mars"
    - ECLIPSE_RELEASE="-Declipse-release=neon"

jdk: oraclejdk8

install: true

addons:
  apt:
    packages:
    - metacity

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - metacity --sm-disable --replace 2> metacity.err &

script: mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B $ECLIPSE_RELEASE
